### PR TITLE
Add HCL

### PR DESCRIPTION
**Pull request by ccakes**
First - thanks for `yj`, it's great!

I was looking today for a tool to use in some script to convert to HCL and couldn't find anything. It seemed _fairly_ straightforward to add it here so I figured I'd have a go.

This is the first time I've written any Go so it's basically a copy-paste job. I vendored the `hcl` package because (a) that's how the TOML dependency is handled and (b) because I don't know how the Go package system works :/

Been using it locally and it seems to work ok enough, at least for my usage. If you want any changes to the PR just let me know.

### CODE REVIEW

**Comment by ccakes** [comment]
A couple of issues with the HCL package, there may be workarounds with better language knowledge.

1. It doesn't have an easy-to-use `hcl.Encode` function, it's possible to build an AST object from JSON though, hence the double conversion is `toHCL`
2. Similarly, I couldn't find a nice way to return a `[]byte` containing the output. Right now I'm just printing the result in `toHCL` and returning nil to main. I dug around for 5mins in the package code but couldn't see an internal method that would be easy to use for me

**Comment by sclevine** [comment]
Many thanks for the PR!

Seems very reasonable for yj to support HCL, given it's popularity (Terraform). I wonder what HCL2 will eventually mean for this integration, but I'm happy to include support for HCL for now.

I agree that converting to JSON to support encoding seems appropriate, given https://github.com/hashicorp/hcl/issues/8.

Just a few things to fix up:
1. Let's leverage `toJSON` instead of copying it here: https://github.com/sclevine/yj/blob/2dd1d82201fa55c637cddfdae345d5d4ad0873ab/main.go#L187-L193
2. You can print this into another `bytes.Buffer` and return the `bytes.Buffer.Bytes()`: https://github.com/sclevine/yj/blob/2dd1d82201fa55c637cddfdae345d5d4ad0873ab/main.go#L196
3. HTML escaping for HCL should be mentioned in the usage (currently it says JSON-only):
https://github.com/sclevine/yj/blob/2dd1d82201fa55c637cddfdae345d5d4ad0873ab/main.go#L189

This project currently uses dep for vendoring, but I'd like it to use go modules instead. Don't worry about including the dependency for now -- I'll handle that with the merge.

This package needs more tests for things outside of the complex YAML normalization it was originally written for. I'd usually ask for tests in a PR, but I'll handle testing HCL when I add integration tests for the rest of the conversions.

**Comment by ccakes** [comment]
Thanks for the review! I've fixed the issues you mentioned but while testing, I've noticed that HCL -> YAML throws an error at times. I haven't had a chance to dig into it yet, but this isn't ready to merge

**Comment by sclevine** [comment]
Fixes look great! Let me know when it's ready.

Happy to help diagnose the HCL -> YAML errors if you could provide more detail.

**Comment by sclevine** [comment]
@ccakes I fixed the HCL -> YAML issue: https://github.com/sclevine/yj/tree/hcl

Mind if I merge this now? 😄

**Comment by ccakes** [comment]
@sclevine Hey! Sorry for the delay, yeah definitely happy if you managed to sort it :blush:

**Comment by sclevine** [comment]
https://github.com/sclevine/yj/releases/tag/v3.0

**Pull request merged**
