### PR TITLE
Add -i to indent JSON output

### PR DESCRIPTION
**Pull request by leahneukirchen**
This is very easy to add, and quite useful.

### CODE REVIEW

**Comment by sclevine** [comment]
Thanks for the contribution!

I also applied your new `-i` flag to TOML output in 885adeb10052a1638006d0355e85fb7e7fa5021a, as TOML has a concept of indentation as well. The indents applied by the TOML parser package are more aggressive than the official TOML spec examples, so this is a good opportunity to disable them by default.

If you're okay with the additional changes, I'll cut a v4.0.0 release this week. (The TOML output change is technically backwards-incompatible, hence the major version bump.)

**Comment by leahneukirchen** [comment]
Sounds useful, thanks.

**Comment by Alhadis** [comment]
You should have indented with tabs, because:

* It's easier to convert them to spaces than vice-versa,
* Raw tabs are illegal in JSON strings, so piping through `sed -e 's/\t/    /g'` or `expand -t4` won't mutilate JSON data,
* They're better than spaces. No, seriously, it's scientifically-proven. Fight me.

**Comment by sclevine** [comment]
I wouldn't want to [deprive anyone of an income](https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/)!

In all seriousness, I'm definitely in the "tabs for indentation, spaces for alignment" camp, which is same philosophy the Go authors appear to have.

[jq defaults to spaces](https://github.com/stedolan/jq/issues/800). Regardless of my personal tastes, I'd like to copy jq's defaults, given that yj is commonly used as a preprocessor for input into jq. I'd consider making this configurable, but I'm not sure if the complexity is warranted (especially given that you could just `yj | jq --tab`).

**Comment by Alhadis** [comment]
> In all seriousness, I'm definitely in the "tabs for indentation, spaces for alignment" camp

Yup, same. But here it's a simple matter of practicality: I'd say that `jq` is making a mistake as well...

**Pull request merged**
